name: DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Test application
        run: npm test

      - name: Build and run Docker image
        run: |
          docker build -t express-hello-world .
          echo "Docker image built successfully"
          echo "Running Docker container..."
          docker run -d -p 3001:3001 --name express-hello-world-container express-hello-world
          echo "Docker container is running on port 3001"